= C++ example project scanned on SonarQube using Azure Pipelines

It is very easy to analyze a C/C++/Objective-C project with SonarQube on Azure DevOps:

. Create a `sonar-project.properties` file to store your configuration
. Install SonarQube extension for your organization:
.. Open Organization settings (in the bottom left corner of organization view)
.. Open "Extensions" page (in the General category)
.. Press "Browse marketplace" and find "SonarQube"
.. Select your organization and click "Install"
. Add the SonarQube connection to your project:
.. Open Project settings (in the bottom left corner)
.. Open "Service connections" page (in the Pipelines category)
.. Press "New connection" and select "SonarQube""
.. Fill in the server URL (e.g.: https://example.com:9000) and the authentication token
.. Name your connection `SonarQube` (to reference it later in `azure-pipelines.yml`)
. In your `azure-pipelines.yml` file:
.. Add the `SonarQubePrepare` task and configure it:
* Specify the `SonarQube Service Endpoint` as `SonarQube` - the connection you created earlier
* Choose "Use standalone scanner" (`scannerMode: 'CLI'`)
* Choose "Manually provide configuration"
* Specify the "Project Key" and the "Sources directory root"
* In "Additional Properties" in the "Advanced" section, add the property `sonar.cfamily.build-wrapper-output` with, as its value, the output directory to which the Build Wrapper should write its results (e.g. `build_wrapper_output_directory`)
.. Add a task to download the https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-4[Build Wrapper]
.. Wrap your compilation with the Build Wrapper
.. Add the `SonarQubeAnalyze` task

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:azure-pipelines.yml[azure-pipelines.yml] to see it in practice. Please be aware that the SonarQube server URL is not completed in this azure-pipelines.yml example.

= Documentation

- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C/C++/Objective-C plugin and its Build Wrapper]
- https://docs.sonarqube.org/latest/analysis/azuredevops-integration/[Documentation of using SonarQube with Azure DevOps]

= Windows\MSBuild

A build of the https://github.com/sc-sq-c-family-examples/code[code repository] on Windows platform using MSBuild build system.

To build the code run:
----
msbuild sonar_scanner_example.vcxproj
----

= Code Description

An example of a flawed C++ code. The https://github.com/sc-sq-c-family-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sc-sq-c-family-examples/code[code repository] is forked into other repositories in https://github.com/sc-sq-c-family-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sc-sq-c-family-examples?q=linux[Linux]
* https://github.com/sc-sq-c-family-examples?q=macos[MacOS]
* https://github.com/sc-sq-c-family-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sc-sq-c-family-examples?q=cmake[CMake]
* https://github.com/sc-sq-c-family-examples?q=autotools[GNU Autotools]
* https://github.com/sc-sq-c-family-examples?q=xcode[Xcode]
* https://github.com/sc-sq-c-family-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sc-sq-c-family-examples?q=azure[Azure DevOps]
* https://github.com/sc-sq-c-family-examples?q=gh-actions[GitHub Actions]
* https://github.com/sc-sq-c-family-examples?q=travis[Travis]
* https://github.com/sc-sq-c-family-examples?q=jenkins[Jenkins]
* https://github.com/sc-sq-c-family-examples?q=gitlab[GitLab CI]
* https://github.com/sc-sq-c-family-examples?q=bitbucket[BitBucket Pipelines]

Configured for analysis on:

* https://github.com/sc-sq-c-family-examples?q=-sq[SonarQube]
* https://github.com/sc-sq-c-family-examples?q=-sc[SonarCloud]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sc-sq-c-family-examples[this GitHub organization] and the relations between its different repositories.
